export interface Matriculas {
  centro_edicacion_superior: string;
  curso_escolar: string;
  facultad: string;
  carrera: string;
  foto: string;
  anno_academico: string;
  tipo_curso: string;
  fecha_matricula: Date | null | string;
  fecha_ingreso_este_ces: Date | null | string;
  fecha_ingreso_edu_super: Date | null | string;
  ci: string;
  serie_letras: string;
  serie_numero: string;
  tomo: number;
  folio: number;
  anno_ci: number;
  fecha_nacimiento: Date | null | string;
  edad: number;
  nombre: string;
  apellido1: string;
  apellido2: string;
  sexo: string;
  color_piel: string;
  ciudad_nacimiento: string;
  pais_nacimiento: string;
  nacionalidad: string;
  orgacizaciones: string;
  estado_civil: string;
  huerfano: boolean;
  discapacidad: string;
  situacion_escolar: string;
  clase_estudiante: string;
  procedencia_escolar: string;
  domicilio: string;
  registro_civil: string;
  provincia: string;
  fecha: Date | null | string;
  sin_sancion: boolean;
  sancionado: string;
  nunca_matriculado: boolean;
  estuve_matriculado: string;
  no_estoy_matriculado: boolean;
  no_soy_graduado: boolean;
  aceptado: boolean;
}

export interface MatriculasAdd {
  centro_edicacion_superior: string;
  curso_escolar: string;
  facultad: string;
  carrera: string;
  foto: string;
  anno_academico: string;
  tipo_curso: string;
  fecha_matricula: Date | null | string;
  fecha_ingreso_este_ces: Date | null | string;
  fecha_ingreso_edu_super: Date | null | string;
  ci: string;
  serie_letras: string;
  serie_numero: string;
  tomo: number;
  folio: number;
  anno_ci: number;
  fecha_nacimiento: Date | null | string;
  edad: number;
  nombre: string;
  apellido1: string;
  apellido2: string;
  sexo: string;
  color_piel: string;
  ciudad_nacimiento: string;
  pais_nacimiento: string;
  nacionalidad: string;
  orgacizaciones: string;
  estado_civil: string;
  huerfano: boolean;
  discapacidad: string;
  situacion_escolar: string;
  clase_estudiante: string;
  procedencia_escolar: string;
  domicilio: string;
  registro_civil: string;
  provincia: string;
  fecha: Date | null | string;
  sin_sancion: boolean;
  sancionado: string;
  nunca_matriculado: boolean;
  estuve_matriculado: string;
  no_estoy_matriculado: boolean;
  no_soy_graduado: boolean;
  aceptado: boolean;
}

export interface MatriculasList {
  id: string;
  centro_edicacion_superior: string;
  curso_escolar: string;
  facultad: string;
  carrera: string;
  foto: string;
  anno_academico: string;
  tipo_curso: string;
  fecha_matricula: Date | null | string;
  fecha_ingreso_este_ces: Date | null | string;
  fecha_ingreso_edu_super: Date | null | string;
  ci: string;
  serie_letras: string;
  serie_numero: string;
  tomo: number;
  folio: number;
  anno_ci: number;
  fecha_nacimiento: Date | null | string;
  edad: number;
  nombre: string;
  apellido1: string;
  apellido2: string;
  sexo: string;
  color_piel: string;
  ciudad_nacimiento: string;
  pais_nacimiento: string;
  nacionalidad: string;
  orgacizaciones: string;
  estado_civil: string;
  huerfano: boolean;
  discapacidad: string;
  situacion_escolar: string;
  clase_estudiante: string;
  procedencia_escolar: string;
  domicilio: string;
  registro_civil: string;
  provincia: string;
  fecha: Date | null | string;
  sin_sancion: boolean;
  sancionado: string;
  nunca_matriculado: boolean;
  estuve_matriculado: string;
  no_estoy_matriculado: boolean;
  no_soy_graduado: boolean;
  aceptado: boolean;
}

export interface MatriculasProps {
  id: string;
  centro_edicacion_superior: string;
  curso_escolar: string;
  facultad: string;
  carrera: string;
  foto: string;
  anno_academico: string;
  tipo_curso: string;
  fecha_matricula: Date | null | string;
  fecha_ingreso_este_ces: Date | null | string;
  fecha_ingreso_edu_super: Date | null | string;
  ci: string;
  serie_letras: string;
  serie_numero: string;
  tomo: number;
  folio: number;
  anno_ci: number;
  fecha_nacimiento: Date | null | string;
  edad: number;
  nombre: string;
  apellido1: string;
  apellido2: string;
  sexo: string;
  color_piel: string;
  ciudad_nacimiento: string;
  pais_nacimiento: string;
  nacionalidad: string;
  orgacizaciones: string;
  estado_civil: string;
  huerfano: boolean;
  discapacidad: string;
  situacion_escolar: string;
  clase_estudiante: string;
  procedencia_escolar: string;
  domicilio: string;
  registro_civil: string;
  provincia: string;
  fecha: Date | null | string;
  sin_sancion: boolean;
  sancionado: string;
  nunca_matriculado: boolean;
  estuve_matriculado: string;
  no_estoy_matriculado: boolean;
  no_soy_graduado: boolean;
  aceptado: boolean;
}
